title: NoCoSMiCC
description: Non-coding somatic mutations in colorectal cancer
theme: jekyll-theme-cayman

# If your site URL is https://rhagan94.github.io/NoCoSMiCC
baseurl: "/NoCoSMiCC"
url: "https://rhagan94.github.io"

# Optional Cayman settings
show_downloads: false
